// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UploadRequestFileType.
const (
	Videomp4       UploadRequestFileType = "video/mp4"
	Videoquicktime UploadRequestFileType = "video/quicktime"
	Videowebm      UploadRequestFileType = "video/webm"
	VideoxMsvideo  UploadRequestFileType = "video/x-msvideo"
)

// Valid indicates whether the value is a known member of the UploadRequestFileType enum.
func (e UploadRequestFileType) Valid() bool {
	switch e {
	case Videomp4:
		return true
	case Videoquicktime:
		return true
	case Videowebm:
		return true
	case VideoxMsvideo:
		return true
	default:
		return false
	}
}

// CreateVideoRequest defines model for CreateVideoRequest.
type CreateVideoRequest struct {
	// Autor Nome do autor/criador do vídeo.
	Autor string `json:"autor"`

	// Descricao Descrição detalhada do vídeo.
	Descricao *string `json:"descricao,omitempty"`

	// Id Identificador único do vídeo (deve coincidir com o id gerado no upload).
	Id openapi_types.UUID `json:"id"`

	// ThumbnailUrl URL da miniatura do vídeo.
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`

	// Titulo Título do vídeo.
	Titulo string `json:"titulo"`

	// UrlS3 URL final do objeto no S3 após o upload.
	UrlS3 string `json:"url_s3"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Código legível do erro.
	Code    string `json:"code"`
	Details *[]struct {
		Field  *string `json:"field,omitempty"`
		Reason *string `json:"reason,omitempty"`
	} `json:"details,omitempty"`

	// Message Mensagem descritiva do erro.
	Message string `json:"message"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// FileName Nome original do arquivo (ex: video.mp4).
	FileName string `json:"fileName"`

	// FileSize Tamanho do arquivo em bytes (máx. 10 GB).
	FileSize *int64 `json:"fileSize,omitempty"`

	// FileType MIME type do arquivo de vídeo.
	FileType UploadRequestFileType `json:"fileType"`
}

// UploadRequestFileType MIME type do arquivo de vídeo.
type UploadRequestFileType string

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ExpiresAt Data/hora de expiração da URL.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// ExpiresIn Tempo de validade da URL em segundos.
	ExpiresIn int `json:"expiresIn"`

	// UploadUrl URL assinada do S3 para upload direto.
	UploadUrl string `json:"uploadUrl"`

	// VideoId Identificador único do vídeo que será criado.
	VideoId openapi_types.UUID `json:"videoId"`
}

// Video defines model for Video.
type Video struct {
	// Autor Nome do autor.
	Autor string `json:"autor"`

	// CreatedAt Data/hora de criação do registro.
	CreatedAt time.Time `json:"createdAt"`

	// Descricao Descrição do vídeo.
	Descricao *string `json:"descricao,omitempty"`

	// Id Identificador único do vídeo.
	Id openapi_types.UUID `json:"id"`

	// LikeCount Número de curtidas.
	LikeCount int `json:"likeCount"`

	// ThumbnailUrl URL da miniatura.
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`

	// Titulo Título do vídeo.
	Titulo string `json:"titulo"`

	// UpdatedAt Data/hora da última atualização.
	UpdatedAt time.Time `json:"updatedAt"`

	// UrlS3 URL do objeto no S3.
	UrlS3 string `json:"url_s3"`

	// ViewCount Número de visualizações.
	ViewCount *int `json:"viewCount,omitempty"`
}

// VideoListResponse defines model for VideoListResponse.
type VideoListResponse struct {
	// NextToken Token para buscar a próxima página (null quando não houver mais).
	NextToken *string `json:"nextToken,omitempty"`
	Videos    []Video `json:"videos"`
}

// VideoResponse defines model for VideoResponse.
type VideoResponse struct {
	Video Video `json:"video"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	// Limit Quantidade máxima de vídeos a retornar.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// NextToken Token de paginação para a próxima página.
	NextToken *string `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// CreateVideoJSONRequestBody defines body for CreateVideo for application/json ContentType.
type CreateVideoJSONRequestBody = CreateVideoRequest

// CreateUploadUrlJSONRequestBody defines body for CreateUploadUrl for application/json ContentType.
type CreateUploadUrlJSONRequestBody = UploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Listar todos os vídeos
	// (GET /videos)
	ListVideos(ctx echo.Context, params ListVideosParams) error
	// Registrar metadados do vídeo
	// (POST /videos)
	CreateVideo(ctx echo.Context) error
	// Iniciar upload de vídeo
	// (POST /videos/upload)
	CreateUploadUrl(ctx echo.Context) error
	// Obter detalhes de um vídeo
	// (GET /videos/{id})
	GetVideoById(ctx echo.Context, id openapi_types.UUID) error
	// Dar like no vídeo
	// (POST /videos/{id}/like)
	LikeVideo(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListVideos converts echo context to params.
func (w *ServerInterfaceWrapper) ListVideos(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "nextToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "nextToken", ctx.QueryParams(), &params.NextToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter nextToken: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListVideos(ctx, params)
	return err
}

// CreateVideo converts echo context to params.
func (w *ServerInterfaceWrapper) CreateVideo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateVideo(ctx)
	return err
}

// CreateUploadUrl converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUploadUrl(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUploadUrl(ctx)
	return err
}

// GetVideoById converts echo context to params.
func (w *ServerInterfaceWrapper) GetVideoById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVideoById(ctx, id)
	return err
}

// LikeVideo converts echo context to params.
func (w *ServerInterfaceWrapper) LikeVideo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LikeVideo(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/videos", wrapper.ListVideos, options.OperationMiddlewares["listVideos"]...)
	router.POST(options.BaseURL+"/videos", wrapper.CreateVideo, options.OperationMiddlewares["createVideo"]...)
	router.POST(options.BaseURL+"/videos/upload", wrapper.CreateUploadUrl, options.OperationMiddlewares["createUploadUrl"]...)
	router.GET(options.BaseURL+"/videos/:id", wrapper.GetVideoById, options.OperationMiddlewares["getVideoById"]...)
	router.POST(options.BaseURL+"/videos/:id/like", wrapper.LikeVideo, options.OperationMiddlewares["likeVideo"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnNbhvJEX6VxiTAagH+DElJlgkEgWwtFlzIP6EkI4ltLIrTRbKt6e5Rdw8tyiCQh8gLGDkEOfhk5OIr",
	"3yRPElTPkJwhh6K0659FkBs57Omurvq+qq+K74JIy0QrVM4G3XeBjcYowX98bBAcvhAcdR+vUrSOniZG",
	"J2icQL8GUqcNfeBoIyMSJ7QKusFTLZFxzfzPzcgI4NrQg8n8A0fdCGoBXoNMYgy6wSWISwxqgYTrU1Qj",
	"Nw66rfZRLZBCLb/XAjdNaLF1RqhRMKvlJ0agN48/8d/m/5z/QzOODuIxcNh2/Av/jHGUWllnwImJprVR",
	"rJW/xF90ep4OsFE28SAMwwqrBN80p8dROTEUkffC/JMSkV5Zw/Y4TpBFWqhIcGFYpCXTTHA2QgNcM6VZ",
	"msQa+Pdlw3n7YThsIdYPo4P9+v4gbNUfhnhY5w/C1oP9o2F4dNAKasFQGwku6AZpKnhQYbIbp3KgQMQX",
	"Jt40/qJ/yjgwKZQAl5qtbhw7l9husymn9UEaXaJr2E4DJNxoBW9tI9KyuTzINhe2N94ko5KNRgS1QKVx",
	"DAPa1pkUq0wWLo0rAn8+/0A/bLPxCaYsMUKiMIsF98ddauKfbafaUUOhIKbT9eANOh+6sw6DZP7RskUU",
	"7+227LWVz26Ld0Mm+5v+XLvDrBYYvEqFQR50XwYZKjKPLq9Xy6n9evk2XSly5IEfjNGmjzbRyuJmTog0",
	"x033PJ5/5GKkWYyj+YcJei+hMetkPD7tnRyf9549/fmHfv9ZP6gkviMM0RHCobSbFgwFxp6Hq42X99vY",
	"ziBYsrC4WmWZY4IMrQPDJnAjdKUjN5yzBbtgDEzpd4nWwqjCQU9Q0Q+SZY+dmEC1j56xCGSi2XfZnb5j",
	"838xPTBiBG7+0Qi/+vaI+witTKmK8YUH3da8PxQxPgWJW1K/NmK0oAKYq5RS6h5ed9mEqgmBdC2XSUzr",
	"y9/KnGwfHOzkJJlzJm4qzDkHCWqsi4agZIOpQ8v25Pz9dYO1Qvbjo7I9B+399tGRz/BLKgnlDnPThExl",
	"0G2FDzoP9ltH7f3QG5g/XZonlMMRmoV95/7pRtR7T35g9ELRQo7F9KVo25eBd08zc0/2+S0O5PLLVSqi",
	"SyckLp9c16X1nyjAK1cX97kdJssgFy5wG1a2JQS8ToRBe+wqKjU4aI41lRVkfh3kZRvYRf+0DJJ22D6s",
	"h4f1duu8ddgNw24Y/rWY7Dg4rOcu2IBIbkRPVWAEiU7kdIgFB4756YQUi6NUcW1LlnQOC7W/EOYsU28t",
	"o2CtULkSOeuwBAzkNYFxYdDpX1waYBDVW+0OkeePf64fy5v6mRgpqtf4h0ajsbMi5JDp3V+8XKXILJr5",
	"e5apvC8hUdZgufJyMaqrK1RB1KvYXyZfq8XqhgMjr5b5TpCTm3KIa2ZwJKxbT/BFnLfvi/O7yuJfL4Z3",
	"qrT7a+EvI3BjcYmPdaoqQvN0/kmi8eSPUuMEhzLTK2l+P8H8vyKTN4Vwwu+AeGDzT7ETEhi4FGJxk6H/",
	"MyL+NkG+JsV/tfa+k76mVIRvdyNuIuzSI//GncC7j2wv5qNipIpk2JonT4V126u5wmt3ri+xqpDS46yu",
	"DVIbgWHAEjP/eE3hT+bvSROyPYItu0pBUW9LuWis0wkaJkHYNVmI05/CQac/HjzuHT558+jhXUDvy0C5",
	"O/i9wWHQDX7XXM06mvmgo5lVhtm6UF9zdr7pVpdtd9dkUXnuYETVoRVn0jqhhhXEPn7ey9y/nq/Zf/72",
	"91xr1FgEHKjqMGSRVjaNHawkp4ehE877f/H2Y7/d8fMelVk0Njut1QgbIblAJ6ggEUE36DTCBqEwATf2",
	"12+uwjHCCjr00WmjgAGLhc3scJpry7RdGLSwF+ix0uxkqkDqk0dkKHkaaCuSLgEB90V2HplgQKJDY4Pu",
	"y/Vj/5SCcpnWoyaA8LnyAANmMrN88Rf0wlWKZkrw801PEAspiE1ZALNrDSGNXdBth6UeYUdvMKtVk4gj",
	"S4D4kpVrH9RNMm0zb8XRoonrsuo1wS3DrQ9QOwyz/l05zFIXJEksIu/g5pu8S17ttxPRpUTiYVu+6uki",
	"5AvH527n4IdgNo3QWk/Og89oWnl8UWEWLWAUIaM0A50h0yyM9DS1qZRgpos7mA3QEolgRNALckS+ntWC",
	"RNsKDpxBPAF6V6ID7mHOkaVyobHfkLoGY3CUjwPPOq/UnuA15rJCXstnBh4rNZbVglomX78vUeaV2iBN",
	"YcwbZPkHrXuk+fSzObxikDwr5zpK5bMNNLY+LxpvC3mue3M9Tm5eA+D+1wTgyQIDqMgYYEJN5u9jwQl9",
	"ZMvDr2fLT/P3DK+FdUVEZiNqiVZqJvg3J+gibIYt9WqZpP3lggLFitp2naqz2qJy5RLQF/ZK9v6I1MbL",
	"bGKw1uLvJQatGCnk9Ov3WRqnlpk6KoHK4SuVaGuBDeEGzXJGnM8DqmdCWzl8UWiMvwSPyzPBO1E4/OyH",
	"b0dFyf/+vxP4LbP4mzKG3EPq/KJ/ukaVnhKRALMEIt6NJe8En+0UeaUSR9eI0a0XO7QJRvMPQxFplmCs",
	"mcWUCb4p9n7ETOs9mvb4Lrm36x+4i4veCZtkQ2mvp0i/ruSUb7XKUC/qql3jqy+us25Fof//Ewv5bqmy",
	"siCU+bH/9TCZ11zfAqKiM6nwfnNq5J3rlkrybODQ5H8qYxm6d2BIk7rvYilZ718ul0Ls/3je1jNc4q06",
	"7TeA4BJiTsAwCjvp8FuAQu+gmVTH+7nRPPXqPhv1FIZXkIiG7/brU526dICNfHzi51eTVrDZYZ6gRTXR",
	"8URIVE6zWEcQlzbuNpv+4Vhb1+2EYeg3er20e33HZwTjbIrFDMYQCU1VmDrpVT+Ugy+/8uz17L8BAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
