// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UploadRequestFileType.
const (
	Videomp4       UploadRequestFileType = "video/mp4"
	Videoquicktime UploadRequestFileType = "video/quicktime"
	Videowebm      UploadRequestFileType = "video/webm"
	VideoxMsvideo  UploadRequestFileType = "video/x-msvideo"
)

// Valid indicates whether the value is a known member of the UploadRequestFileType enum.
func (e UploadRequestFileType) Valid() bool {
	switch e {
	case Videomp4:
		return true
	case Videoquicktime:
		return true
	case Videowebm:
		return true
	case VideoxMsvideo:
		return true
	default:
		return false
	}
}

// CreateVideoRequest defines model for CreateVideoRequest.
type CreateVideoRequest struct {
	// Autor Nome do autor/criador do vídeo.
	Autor string `json:"autor"`

	// Descricao Descrição detalhada do vídeo.
	Descricao *string `json:"descricao,omitempty"`

	// Id Identificador único do vídeo (deve coincidir com o id gerado no upload).
	Id openapi_types.UUID `json:"id"`

	// ThumbnailUrl URL da miniatura do vídeo.
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`

	// Titulo Título do vídeo.
	Titulo string `json:"titulo"`

	// UrlS3 URL final do objeto no S3 após o upload.
	UrlS3 string `json:"url_s3"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Código legível do erro.
	Code    string `json:"code"`
	Details *[]struct {
		Field  *string `json:"field,omitempty"`
		Reason *string `json:"reason,omitempty"`
	} `json:"details,omitempty"`

	// Message Mensagem descritiva do erro.
	Message string `json:"message"`
}

// UploadRequest defines model for UploadRequest.
type UploadRequest struct {
	// FileName Nome original do arquivo (ex: video.mp4).
	FileName string `json:"fileName"`

	// FileSize Tamanho do arquivo em bytes (máx. 10 GB).
	FileSize *int64 `json:"fileSize,omitempty"`

	// FileType MIME type do arquivo de vídeo.
	FileType UploadRequestFileType `json:"fileType"`
}

// UploadRequestFileType MIME type do arquivo de vídeo.
type UploadRequestFileType string

// UploadResponse defines model for UploadResponse.
type UploadResponse struct {
	// ExpiresAt Data/hora de expiração da URL.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// ExpiresIn Tempo de validade da URL em segundos.
	ExpiresIn int `json:"expiresIn"`

	// UploadUrl URL assinada do S3 para upload direto.
	UploadUrl string `json:"uploadUrl"`

	// VideoId Identificador único do vídeo que será criado.
	VideoId openapi_types.UUID `json:"videoId"`
}

// Video defines model for Video.
type Video struct {
	// Autor Nome do autor.
	Autor string `json:"autor"`

	// CreatedAt Data/hora de criação do registro.
	CreatedAt time.Time `json:"createdAt"`

	// Descricao Descrição do vídeo.
	Descricao *string `json:"descricao,omitempty"`

	// Id Identificador único do vídeo.
	Id openapi_types.UUID `json:"id"`

	// ThumbnailUrl URL da miniatura.
	ThumbnailUrl *string `json:"thumbnailUrl,omitempty"`

	// Titulo Título do vídeo.
	Titulo string `json:"titulo"`

	// UpdatedAt Data/hora da última atualização.
	UpdatedAt time.Time `json:"updatedAt"`

	// UrlS3 URL do objeto no S3.
	UrlS3 string `json:"url_s3"`

	// ViewCount Número de visualizações.
	ViewCount *int `json:"viewCount,omitempty"`
}

// VideoListResponse defines model for VideoListResponse.
type VideoListResponse struct {
	// NextToken Token para buscar a próxima página (null quando não houver mais).
	NextToken *string `json:"nextToken,omitempty"`
	Videos    []Video `json:"videos"`
}

// VideoResponse defines model for VideoResponse.
type VideoResponse struct {
	Video Video `json:"video"`
}

// ListVideosParams defines parameters for ListVideos.
type ListVideosParams struct {
	// Limit Quantidade máxima de vídeos a retornar.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// NextToken Token de paginação para a próxima página.
	NextToken *string `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// CreateVideoJSONRequestBody defines body for CreateVideo for application/json ContentType.
type CreateVideoJSONRequestBody = CreateVideoRequest

// CreateUploadUrlJSONRequestBody defines body for CreateUploadUrl for application/json ContentType.
type CreateUploadUrlJSONRequestBody = UploadRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Listar todos os vídeos
	// (GET /videos)
	ListVideos(ctx echo.Context, params ListVideosParams) error
	// Registrar metadados do vídeo
	// (POST /videos)
	CreateVideo(ctx echo.Context) error
	// Iniciar upload de vídeo
	// (POST /videos/upload)
	CreateUploadUrl(ctx echo.Context) error
	// Obter detalhes de um vídeo
	// (GET /videos/{id})
	GetVideoById(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListVideos converts echo context to params.
func (w *ServerInterfaceWrapper) ListVideos(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVideosParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "nextToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "nextToken", ctx.QueryParams(), &params.NextToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter nextToken: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListVideos(ctx, params)
	return err
}

// CreateVideo converts echo context to params.
func (w *ServerInterfaceWrapper) CreateVideo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateVideo(ctx)
	return err
}

// CreateUploadUrl converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUploadUrl(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUploadUrl(ctx)
	return err
}

// GetVideoById converts echo context to params.
func (w *ServerInterfaceWrapper) GetVideoById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVideoById(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/videos", wrapper.ListVideos, options.OperationMiddlewares["listVideos"]...)
	router.POST(options.BaseURL+"/videos", wrapper.CreateVideo, options.OperationMiddlewares["createVideo"]...)
	router.POST(options.BaseURL+"/videos/upload", wrapper.CreateUploadUrl, options.OperationMiddlewares["createUploadUrl"]...)
	router.GET(options.BaseURL+"/videos/:id", wrapper.GetVideoById, options.OperationMiddlewares["getVideoById"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fndbhu78X8VYv9/4DiAPlaS7TgCisKJg0AHzkdlO2ibBAej5UhisiTXJFexHAjoQ/QFgl4UvchV0Jvc",
	"6k36JMVwV9KutLLsc/Jx0DuJyyV/nPnNzG+4H4JIy0QrVM4G3Q+BjcYowf98ZBAcvhQcdR8vU7SORhOj",
	"EzROoJ8DqdOGfnC0kRGJE1oF3eCZlsi4Zv5xMzICuDY0MJl/4qgbQS3AK5BJjEE3eAfiHQa1QMLVKaqR",
	"GwfdVvuoFkihlv9rgZsmNNk6I9QomNXyHSPQm9uf+H/zf87/oRlHB/EYOGzb/qUfYxylVtYZcGKiaW4U",
	"a+UP8RednqcDbJQhHoRhWIFK8E04PY7KiaGIvBXmX5SI9AoN2+M4QRZpoSLBhWGRlkwzwdkIDXDNlGZp",
	"Emvg98rAeftBOGwh1g+jg/36/iBs1R+EeFjn98PW/f2jYXh00ApqwVAbCS7oBmkqeFAB2Y1TOVAg4gsT",
	"b4K/6J8yDkwKJcClZqsZx84ltttsyml9kEbv0DVspwESrrWC97YRadlcbmSbC+yNt8mohNGIoBaoNI5h",
	"QMs6k2IVZOHSuMLx5/NP9GAbxqeYssQIicIsJtydd6mJf7GdakMNhYKYdteDt+i86846DJL5Z8sWXryz",
	"2bLXVja7yd8Nmexv2nPtDLNaYPAyFQZ50H0VZKzILLo8Xi0P7TfLt+lIkSMLPDZGmz7aRCuLmzkh0hw3",
	"zfNo/pmLkWYxjuafJuithMasB+Pxae/k+Lz3/Nkvj/v95/2gMvAdcYi2EA6l3UQwFBj7OFwtvDzfxnIG",
	"wRLC4myVZY4JMrQODJvAtdCVhtwwzhbugjEwpecSrYVRhYGeoqIHkmXDTkyg2kbPWQQy0eyn7Ew/sfm/",
	"mB4YMQI3/2yEn32zx72HVlCqfHzhSbc17w9FjM9A4pbUr40YLUIBzGVKKXUPr7psQtWESLqWyySm9eWz",
	"cky2Dw52xiTBORPXFXDOQYIa6yIQlGwwdWjZnpx/vGqwVsiePCzjOWjvt4+OfIZfhpJQ7jCHJmQqg24r",
	"vN+5v986au+HHmA+uoQnlMMRmgW+cz+64fXe08eMXigi5FhMX4qWfRV48zQz82S/3+NALv9cpiJ654TE",
	"5chVXVr/ixy8MnVxnZtpsnRy4QA3cWVbQsCrRBi0x66iUoOD5lhTWUHm50FetoFd9E/LJGmH7cN6eFhv",
	"t85bh90w7IbhX4vJjoPDem6CDYrkIHqqgiNI4URGh1hw4JjvTkyxOEoV17aEpHNYqP0FN2eZemsZBWuF",
	"ypXIWYclYCCvCYwLg07/6tIAg6jeancoeP745/qxvK6fiZGieo1/aDQaOytCTpne3cXLZYrMopl/ZJnK",
	"+xYSZY2WKysXvbo6QhVFvYr9dfK1WqxuGDDyapnvJDmZKae4ZgZHwrr1BF/kefuuPL+tLP7tYninSru7",
	"Fv49CNz/FVm7KVwTfguGApt/iZ2QwMClEIvrjK1fkaE3Ceg16fybtfKt9DClDnz/SKeqwjTP5l8kmqw8",
	"CLu0yL+xXBIq6sFdZHYxfxQ9tTWXnQrrtldchVfuXL/DqmJHw1ntGaQ2AsOAJWb++Ypcnsw/km5je0RV",
	"dpmCov6T8sVYpxM0TIKwa9INpz+Hg05/PHjUO3z69uGD2xDdp+qygv9/g8OgG/xfc3Uf0cwvI5pZ9p6t",
	"i+k1A+eLbjXZdnNNFtXhFiCqNq3Yk+YJNawI5uMXvcz86zmV/edvf8/1QI1FwIEqA0MWaWXT2MFKFnrq",
	"OeG8/RdvP/LLHb/oUSlEY7PdWo2wEZIJdIIKEhF0g04jbBDzEnBjf/zmyh0jrAiBPjptFDBgsbAZDqe5",
	"tkzbBaAFXqBhpdnJVIHUJw8JKFkaaCmSFwER92W2H0EwINGhsUH31fq2f0pBuUyPkVAnfq4swICZDJYv",
	"0IJeuEzRTIl+vjEJYiEFRVPmwOxYQ0hjF3TbYUnH79Dvs1p1EHFkCVC8ZCXVO3UzmLbBW8VoEeK69HlD",
	"dMt46x3UDsOsx1YOs3QFSRKLyBu4+TbvZFfr7WR0KZF42paPerpw+cLwudk5+Isqm0ZorQ/Og68IrXzF",
	"UAGLJjDykFGagc6YaRYgfZjaVEow08UZzAZpKYhgRNQLcka+mdWCRNuKGDiDeAL0rkQH3NOcI0vlQge/",
	"JQUMxuAov7I767xWe4LXmMuKdy3v6z1XaizL/7VMYt4rhcxrtRE0havYIMs/aN1DzadfzeAVl72zcq6j",
	"VD7bYGPr67LxJpfn2jTXzGTmNQLuf08Cniw4gIrAABNqMv8YC07sIywPvh+Wn+cfGV4J64qMzK6RJVqp",
	"meA/PEAXbjNsqVHLQdpfTiiEWFHProfqrLaoXLns84W9MnqfILXaMuvq19rwvcSgFSOFnJ7ey9I4tbXU",
	"9QhUDl+rRFsLbAjXaJb3uHnPXn1vszWGLwrN67eI4/K93a1COPzqm29nRcn+/vsG/J6j+IdGDJmH1PlF",
	"/3QtVHpKRALMkoh4uyj5IPhsp8grlTg6RoxuvdihTTCafxpS755grJnFlAm+KfaeYKb1Hk57fJfc2/WV",
	"7OKid8Im2cWx11OkX1dyyrdXZaoXddWuK6ZvrrNuZKH/RomFfLdUWZkTyvGx//04mddc3wKioj2p8P7w",
	"0Mg71y2V5PnAock//GKZupURQi+jmVTT8oXRPPWiLevaC/cQkIiGb+LqU526dICNvCv2VxGTVrDZOJyg",
	"RTXR8URIVE6zWEcQlxbuNpt+cKyt63bCMPQLvVniXl/xOQVcdiHBDMYQCU3JlRqklczNYyQ/8uzN7L8B",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
