/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateVideoRequest { 
    /**
     * Identificador único do vídeo (deve coincidir com o id gerado no upload).
     */
    id: string;
    /**
     * Título do vídeo.
     */
    titulo: string;
    /**
     * Descrição detalhada do vídeo.
     */
    descricao?: string;
    /**
     * URL final do objeto no S3 após o upload.
     */
    url_s3: string;
    /**
     * Nome do autor/criador do vídeo.
     */
    autor: string;
    /**
     * URL da miniatura do vídeo.
     */
    thumbnailUrl?: string | null;
}

