/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseDetailsInner } from './errorResponseDetailsInner';


export interface ErrorResponse { 
    /**
     * Código legível do erro.
     */
    code: string;
    /**
     * Mensagem descritiva do erro.
     */
    message: string;
    details?: Array<ErrorResponseDetailsInner> | null;
}

