/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadRequest { 
    /**
     * Nome original do arquivo (ex: video.mp4).
     */
    fileName: string;
    /**
     * MIME type do arquivo de vídeo.
     */
    fileType: UploadRequest.FileTypeEnum;
    /**
     * Tamanho do arquivo em bytes (máx. 10 GB).
     */
    fileSize?: number;
}
export namespace UploadRequest {
    export const FileTypeEnum = {
        VideoMp4: 'video/mp4',
        VideoWebm: 'video/webm',
        VideoQuicktime: 'video/quicktime',
        VideoXMsvideo: 'video/x-msvideo'
    } as const;
    export type FileTypeEnum = typeof FileTypeEnum[keyof typeof FileTypeEnum];
}


