/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadResponse { 
    /**
     * URL assinada do S3 para upload direto.
     */
    uploadUrl: string;
    /**
     * Identificador único do vídeo que será criado.
     */
    videoId: string;
    /**
     * Tempo de validade da URL em segundos.
     */
    expiresIn: number;
    /**
     * Data/hora de expiração da URL.
     */
    expiresAt?: string;
}

