/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Video } from './video';


export interface VideoListResponse { 
    videos: Array<Video>;
    /**
     * Token para buscar a próxima página (null quando não houver mais).
     */
    nextToken?: string | null;
}

