/**
 * YouTube Clone API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Video { 
    /**
     * Identificador único do vídeo.
     */
    id: string;
    /**
     * Título do vídeo.
     */
    titulo: string;
    /**
     * Descrição do vídeo.
     */
    descricao?: string | null;
    /**
     * URL do objeto no S3.
     */
    url_s3: string;
    /**
     * Nome do autor.
     */
    autor: string;
    /**
     * URL da miniatura.
     */
    thumbnailUrl?: string | null;
    /**
     * Número de visualizações.
     */
    viewCount?: number;
    /**
     * Número de curtidas.
     */
    likeCount: number;
    /**
     * Data/hora de criação do registro.
     */
    createdAt: string;
    /**
     * Data/hora da última atualização.
     */
    updatedAt: string;
}

